### ISSUE TITLE
msm on ubuntu 16.04

### ISSUE THREAD

**Issue by jcupitt** [ecr05/MSM_HOCR#10]
Hello, I've made a Dockerfile that builds MSM from source on Ubuntu 16.04, perhaps it could be useful:

https://github.com/jcupitt/docker-builds/blob/master/msm-fsl6-ubuntu16.04/Dockerfile

I had to make a few small changes to FSL to get it to work with Ubuntu 16.04, and also change the libs list for MSM itself:

https://github.com/ecr05/MSM_HOCR/commit/a74ada542b9845ddbe1758a8f276e4e3496c4dd3

There's probably a better way to get it to link, of course.

**Comment by ecr05** [comment]
Hi John, What changes did you need to make? MSM is now FSL6 compatible.

**Comment by ecr05** [comment]
Hey, Why were those changes needed?

**Comment by jcupitt** [comment]
The Dockerfile has comments in, but the process is:

- Ubuntu 16.04 is not supported by the FSL6 makefiles. 
- I made a config for it from `linux_64-gcc4.8` (to make `gnu_64-gcc4.8`).
- That has `-lopenblas` in `LIB_NEWMAT` (incorrectly, I think), but that ends up `USRLDFLAGS` in MSM, so it won't link since it'll come before the object that needs the library.
- I added `-lopenblas` to the end of the MSM link line to fix this.
- `-lopenblas` in turn needs `libgfortran.so.3`, but FSL is missing a symlink for `libgfortran.so`, so `-lgfortran` won't work.
- I added the symlink to FSL, but another fix would be to append `/usr/local/fsl/lib/libgfortran.so.3` to the MSM link line.

**Comment by ShacharGal** [comment]
were also having some trouble compiling MSM on ubuntu 18.04, with an error regarding newmat:
/usr/local/fsl/include/utils/log.h:85:10: fatal error: newmatap.h: No such file or directory

you think this process could work for us as well?

**Comment by jcupitt** [comment]
Yes, it should work. I've updated it to use FSL 6.0.1, which is quite a bit better.

**Comment by ShacharGal** [comment]
im using fsl 6.0.0
would it be a problem?

**Comment by ecr05** [comment]
Unfortunately FSL is changing rapidly in the backend at the moment. 
I don't know that this is the same problem.  Try it and if it doesn't work post to FSL list and I will try and help you fix it with their support.

**Comment by jcupitt** [comment]
An older version of that docker script worked for 6.0.0, the current version is updated for 6.0.1.

Old 6.0.0 build:

https://github.com/jcupitt/docker-builds/tree/549b050a1e18f022cfe187b28cc4293a04202a78/msm-fsl6-ubuntu16.04

The current one works for 6.0.2 (sorry, not 6.0.1), I built it myself yesterday.

**Comment by ShacharGal** [comment]
we got this error:

/bin/sh: 1: cannot open /usr/local/src/fsl/fsl.sh.patch: No such file
The command '/bin/sh -c cd $fsl_prefix/etc/fslconf     && patch < /usr/local/src/fsl/fsl.sh.patch' returned a non-zero code: 2

do you know where i can get fsl.sh.patch?

**Comment by ecr05** [comment]
Really you need to post these questions to the FSL list. I do not know the answer but they will.

**Comment by ecr05** [comment]
Incidentally - wont the binaries from the release tab work for you?

**Comment by ecr05** [comment]
Incidentally - wont the binaries from the release tab work for you?

**Comment by ShacharGal** [comment]
indeed it does.
i didnt know it was an option....

thanks
